[package]
name = "leitsys_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tower-http = { version = "0.6", features = ["cors", "trace"] }

tokio = { version = "1", features = ["full"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }

sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }

bcrypt = "0.15"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto"] }
tower-cookies = { version = "0.10", features = ["axum-core"] }

tracing = "0.1"
tracing-subscriber = "0.3"

utoipa = { version = "4", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "7", features = ["axum", "vendored"] }

anyhow = "1.0.102"
dotenvy = "0.15"